every day at 0:05 AM:
  if now is 2025-09-02:
    execute console command "border 10000"

  else if now is 2025-09-03:
    execute console command "border 9000"

  else if now is 2025-09-04:
    execute console command "border 8000"

  else if now is 2025-09-05:
    execute console command "border 7000"

  else if now is 2025-09-06:
    execute console command "border 6000"

  else if now is 2025-09-07:
    execute console command "border 5000"

  else if now is 2025-09-08:
    execute console command "border 4000"

  else if now is 2025-09-09:
    execute console command "border 3000"

  else if now is 2025-09-10:
    execute console command "border 2000"

  else if now is 2025-09-11:
    execute console command "border 1000"

  else if now is 2025-09-12:
    execute console command "border 500"
