options:
  prefix: &a[Border]

command /border <radius: integer>:
  permission: op
  trigger:
    set {_radius} to arg 1
    set {_worldborder_wide} to {_radius} * 2

    execute console command "chunky radius %{_radius}%"
    execute console command "chunky border add"
    wait 1 second

    execute console command "worldborder set %{_worldborder_wide}%"

    send "{@prefix} &fBorder successfully updated to radius %{_radius}%." to console
    send "{@prefix} &fBorder successfully updated to radius %{_radius}%." to sender
