# ==============================================================================
# Script Name: border.sk
# Description: Manages the world border radius using ChunkyBorder.
#              It sets the Chunky border radius, starts the border generation,
#              and sets the vanilla world border to twice the radius.
# ==============================================================================

# ------------------------------------------------------------------------------
# Options
# ------------------------------------------------------------------------------
options:
  prefix: &a[Border]

# ------------------------------------------------------------------------------
# Command: /border
# Purpose: Sets the world border radius and updates ChunkyBorder and vanilla border.
# Permission: op
# Usage:
#   /border <radius>
# Arguments:
#   - <radius>: The radius of the border in blocks (integer).
# ------------------------------------------------------------------------------
command /border <radius: integer>:
  permission: op
  trigger:
    set {_radius} to arg 1
    set {_worldborder_wide} to {_radius} * 2

    execute console command "chunky radius %{_radius}%"
    execute console command "chunky border add"
    wait 1 second

    execute console command "worldborder set %{_worldborder_wide}%"

    send "{@prefix} &fBorder successfully updated to radius %{_radius}%." to console
    send "{@prefix} &fBorder successfully updated to radius %{_radius}%." to sender
